- name: Install Packages I like   # These should exist in most repositories
  apt:
    name:
      - fish
      - mc
      - fzf
      - neofetch

- name: Install nice-to-have Packages   # These might not exist, checking before installing.
  block:
    - name: Check if btop exists in repo
      shell: dpkg-query -W 'btop'
      ignore_errors: true
      register: btop_exists

    - name: Install btop
      when: btop_exists is not failed
      apt:
        name: btop  

    - name: Check if bat exists in repo
      shell: dpkg-query -W 'bat'
      ignore_errors: true
      register: bat_exists

    - name: Install bat
      when: bat_exists is not failed
      apt:
        name: bat

    - name: Check if eza exists in repo
      shell: dpkg-query -W 'eza'
      ignore_errors: true
      register: eza_exists

    - name: Install eza
      when: eza_exists is not failed
      apt:
        name: eza
        
- include_tasks: copy-dots.yml
