- name: Install Packages I like   # These should exist in most repositories
  apt:
    name: "{{ required_packages }}"

- name: Install nice-to-have Packages   # These might not exist, checking before installing.
  include_tasks:
    file: apt-check-install.yml
  loop: "{{ optional_packages }}"
  loop_control:
    label: Checking/installing {{ item }}

- name: Apply preferred user settings
  include_tasks:
    file: user-settings.yml
