- name: Install Packages I like   # These should exist in most repositories
  apt:
    name:
      - fish
      - mc
      - fzf
      - neofetch

- name: Install nice-to-have Packages   # These might not exist, checking before installing.
  block:
    - name: Check if btop exists in repo
      shell: dpkg-query -W 'btop'
      register: btop_check
      failed_when: false
      changed_when: false

    - name: Install btop
      when: btop_check.rc == 0
      apt:
        name: btop  

    - name: Check if bat exists in repo
      shell: dpkg-query -W 'bat'
      register: bat_check
      failed_when: false
      changed_when: false

    - name: Install bat
      when: bat_check.rc == 0
      apt:
        name: bat

    - name: Check if eza exists in repo
      shell: dpkg-query -W 'eza'
      register: eza_check
      failed_when: false
      changed_when: false

    - name: Install eza
      when: eza_check.rc == 0
      apt:
        name: eza

- include_tasks: copy-dots.yml
